repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.286
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
